/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SanPhamRouteImport } from './routes/san-pham'
import { Route as CongTrinhDaThiCongRouteImport } from './routes/cong-trinh-da-thi-cong'
import { Route as IndexRouteImport } from './routes/index'

const SanPhamRoute = SanPhamRouteImport.update({
  id: '/san-pham',
  path: '/san-pham',
  getParentRoute: () => rootRouteImport,
} as any)
const CongTrinhDaThiCongRoute = CongTrinhDaThiCongRouteImport.update({
  id: '/cong-trinh-da-thi-cong',
  path: '/cong-trinh-da-thi-cong',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cong-trinh-da-thi-cong': typeof CongTrinhDaThiCongRoute
  '/san-pham': typeof SanPhamRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cong-trinh-da-thi-cong': typeof CongTrinhDaThiCongRoute
  '/san-pham': typeof SanPhamRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cong-trinh-da-thi-cong': typeof CongTrinhDaThiCongRoute
  '/san-pham': typeof SanPhamRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/cong-trinh-da-thi-cong' | '/san-pham'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/cong-trinh-da-thi-cong' | '/san-pham'
  id: '__root__' | '/' | '/cong-trinh-da-thi-cong' | '/san-pham'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CongTrinhDaThiCongRoute: typeof CongTrinhDaThiCongRoute
  SanPhamRoute: typeof SanPhamRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/san-pham': {
      id: '/san-pham'
      path: '/san-pham'
      fullPath: '/san-pham'
      preLoaderRoute: typeof SanPhamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cong-trinh-da-thi-cong': {
      id: '/cong-trinh-da-thi-cong'
      path: '/cong-trinh-da-thi-cong'
      fullPath: '/cong-trinh-da-thi-cong'
      preLoaderRoute: typeof CongTrinhDaThiCongRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CongTrinhDaThiCongRoute: CongTrinhDaThiCongRoute,
  SanPhamRoute: SanPhamRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
